name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    # strategy:
    #   matrix:
    #     targetplatform: [x86, x64]

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: cargo build --release

    # - name: Look around
    #   run: |
    #     ls
    #     ls target
    #     ls target/debug

    - name: Lint
      run: cargo clippy --release -- -W clippy::pedantic -W clippy::nursery -W clippy::expect_used

    - uses: actions/upload-artifact@v3
      with:
        name: sharextended
        path: ./target/release/sharextended.exe